### ISSUE TITLE
Kitti3 does not work when focusing primary (right) monitor

### ISSUE THREAD

**Issue by abou123** [LandingEllipse/kitti3#10]
I recently upgraded to a multimonitor setup, and have been using kitti3 for quite some time now.  When I move my mouse to my (new) primary monitor and try to access kitti3, all it does is unfocus whatever window was focused previously.  When I move my mouse to my secondary monitor and try to access kitti3, it works just fine.  I should note that my secondary monitor is setup to be on the left of my primary monitor.  Is there any way to get kitti3 working on both monitors (as in whichever my mouse is in)?  Or at least just my primary monitor?
Edit:  just tried making my primary monitor (in software) to the left of my secondary monitor, and kitti3 worked on my primary monitor then but not on my secondary, so it seems that it doesn't work on whichever monitor is seen as the "left" monitor

**Comment by LandingEllipse** [comment]
Hi @abou123 ,

Thanks for taking the time to create an issue. I'm unfortunately having some trouble reproducing the issue you're describing; on my system using (A)RandR to manage multiple monitors, everything is working as expected (i.e. triggering kitti3 through its keybinding either toggles the visibility of Kitty or brings the Kitty instance over to the focused workspace if it was previously on a different workspace/monitor).

Can you please elaborate on what you mean by "try to access kitti3"? Perhaps there's something we're doing differently.

Also, can you please post the output of `xrandr -q`? I'm assuming you're using RandR but it almost sounds like i3 is treating your two monitors as a single large workspace, which is confusing...

All the best,
Ariel

**Comment by abou123** [comment]
Thanks for making such a great tool Ariel (@LandingEllipse),

When I say accessing kitti3, I mean using the keyboard shortcut (mod+n or F12 in my case) that I have bound to make kitti3 show up on my workspace.
relevant part of my i3 config
```
# use a dropdown terminal
        exec_always --no-startup-id kitti3 -n theVoid -p top -s 1.0 0.32
        bindsym $mod+n nop theVoid
        bindsym F12 nop theVoid
```
and here's the output of xrandr -q
```
Screen 0: minimum 8 x 8, current 5120 x 1440, maximum 32767 x 32767
DVI-D-0 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 connected primary 2560x1440+2560+0 (normal left inverted right x axis y axis) 600mm x 340mm
   2560x1440     59.95 + 165.00*  144.00   119.99    75.00  
   1920x1080     60.00  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1400x1050     59.98  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1152x864      59.96  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32  
   640x480       75.00    72.81    59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
```

Stay safe out there,
Daisy

**Comment by LandingEllipse** [comment]
Hi again @abou123 and thanks for your patience.

I'm afraid I still haven't been able to reproduce this, even when recreating your RandR setup and Kitti3 parameters, both of which fall within the norm and work perfectly fine for me. 

Can you confirm that you're using the latest version of Kitti3 (0.2.6)? We've had some layout issues in the past that were addressed in that release. 

If you're already up to date and still keen on sorting out this issue then we might have to try doing some debugging on your end. Swapping out your i3wm config for a stock one (with the basic Kitti3 lines inserted) would be the starting point. If it's still acting up then using the `i3-msg` tool is the next step that comes to mind. With this you can see if there are any differences between toggling kitti3 in your primary vs secondary monitor. 

I'd perhaps start with something like `i3-msg -m -t subscribe '[ "window" ]` (spit out all events associated with windows) and see what you find. For sanity though I'd strongly recommend doing some parsing with jq (might have to install that): `jq 'select(.container.window_properties.instance == "theVoid")' <(i3-msg -m -t subscribe '[ "window" ]')`. Notice that we're only displaying events related to the Kitty instance named "theVoid". Run this in a separate (permanently visible) terminal and trigger Kitti3 to catch the events. To just spit out the output monitor and window coordinates, you can restrict the output: `jq 'select(.container.window_properties.instance == "theVoid") | {"output": .container.output}, .container.rect' <(i3-msg -m -t subscribe '[ "window" ]')`. 

For reference, with your geometry and Kitti3 parameters I get the following output:

Bringing up Kitti3 on the left monitor:
```
{
  "output": "eDP1"
}
{
  "x": 0,
  "y": 0,
  "width": 2560,
  "height": 452
}
```
Bringing up Kitti3 on the right monitor:
```
{
  "output": "DP1-2"
}
{
  "x": 2560,
  "y": 0,
  "width": 2560,
  "height": 461
}
```
(The heights are slightly different as the status bar is present on the primary screen and its height is subtracted when calculating the available height.)

Best regards,
Ariel

**Comment by abou123** [comment]
Hey again @LandingEllipse,
I just updated my system and rebooted (didn't change my configs at all), and for some reason everything's working properly now.  Sorry to have put you through all of this.

Thanks for all of this,
Daisy
