### ISSUE TITLE
After system update, kitti3 no longer likes me.  i3ipc socket does not exist?

### ISSUE THREAD

**Issue by anoduck** [LandingEllipse/kitti3#24]
So, admittedly, a big update came through on my system which changed the default python version from 3.9 to 3.10. Kitti3 would not run
when called with the i3 keybind, but would run in the terminal for some reason. This caused me to do some investigating, and inevitably
trying to reinstall kitti3. Unfortunately, once I tried to install it, I always received the same error message when I attempted to run
it. It appears i3ipc is not creating it's socket, but this is just a guess

``` bash
Traceback (most recent call last):
  File "/usr/local/bin/kitti3", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/kitti3/main.py", line 312, in cli
    kitti3 = Kitti3(
  File "/usr/local/lib/python3.10/site-packages/kitti3/main.py", line 78, in __init__
    self.i3 = i3ipc.Connection()
  File "/usr/local/lib/python3.10/site-packages/i3ipc/connection.py", line 74, in __init__
    self._cmd_socket.connect(self._socket_path)
FileNotFoundError: [Errno 2] No such file or directory
```

Any suggestions?

**Comment by anoduck** [comment]
Most definitely, resolved.

**Comment by ar7ch** [comment]
Hey, I have the same problem with Python 3.12 and kitti3 installed using `pipx`. Could you please share how you resolved it?

**Comment by anoduck** [comment]
@ar7ch Have you checked to ensure your `XDG_RUNTIME_DIR` is set somewhere in your environment (ex. zshrc, bashrc, .profile, etc, etc...), and if it is correct?

You can check this with a simple `echo $XDG_RUNTIME_DIR`.

This variable, `ipc-socket`, in your i3 config file is required for kitti3 to work, because it is how kitti3 connects to your current i3 session through the i3 ipc-socket. If this value is off or not in your config, then kitti3 won't work.

```conf
ipc-socket /tmp/runtime-<$YOUR USERNAME HERE>/i3/ipc-socket.socket
```

You can run `cat ~/.config/i3/conf | grep runtime` to check the above.

The i3 folder `/tmp/runtime-<$USERNAME>/i3`, which contains your `ipc-socket.socket` file, should reside within your `XDG_RUNTIME_DIR`.
