### ISSUE TITLE
Kitty font size should reflect relative monitor resolution

### ISSUE THREAD

**Issue by LandingEllipse** [LandingEllipse/kitti3#4]
In multi-monitor, multi-resolution setups, Kitti3 might be able to capitalise on Kitty's remote control capabilities to adjust the latter's font size when displayed on monitors with resolutions different than the "native" (main screen) resolution.

ToDo:

- [ ] research Kitty remote control functionality
- [ ] map out relevant transitions / scenarios
- [ ] implement font size transitions

**Comment by kovidgoyal** [comment]
FYI kitty font sizes are in pts and *should* adjust automatically when moving to monitors with different resolutions, so you get the same physical sized text regardless of monitor DPI.

**Comment by LandingEllipse** [comment]
Closing as here be dragons, and I might want to take kitti3 in a more general direction (e.g. support other terminals / windows users might want to float-manage).
